steps:

- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 900s
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      apt-get update
      apt-get install jq -y
      echo -n $(gcloud run services describe ${_RUN_SERVICE} \
        --region ${_GCP_REGION} \
        --format json 2>/dev/null | jq -r '.status.latestReadyRevisionName') \
        > /workspace/latest-revision.txt

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_REPO}:${_TAG}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_REPO}:${_TAG}']

- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 900s
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      gcloud run deploy ${_RUN_SERVICE} \
        --image ${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_REPO}:${_TAG} \
        --region ${_GCP_REGION} \
        --port ${_PORT} \
        --set-env-vars ${_ENV_VARS} \
        --concurrency ${_CONCURRENCY} \
        --cpu ${_CPU} \
        --memory ${_MEMORY_GB} \
        --timeout ${_TIMEOUT} \
        --min-instances ${_MIN_INSTANCES} \
        --max-instances ${_MAX_INSTANCES} \
        --ingress ${_INGRESS_SETTINGS} \
        --platform managed \
        --no-use-http2 \
        --allow-unauthenticated \
        --tag ${_TAG}

- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 900s
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      apt-get update
      apt-get install jq -y
      echo $(gcloud run services describe ${_RUN_SERVICE} \
        --region ${_GCP_REGION} \
        --format json 2>/dev/null | jq -r '.status.latestReadyRevisionName') \
        > /workspace/new-latest-revision.txt

- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 900s
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      if [ -s /workspace/latest-revision.txt ]; then gcloud run services update-traffic ${_RUN_SERVICE} \
        --region ${_GCP_REGION} \
        --to-revisions=$(cat /workspace/latest-revision.txt)=50,$(cat /workspace/new-latest-revision.txt)=50; fi

timeout: 1200s
